### ISSUE TITLE
How do I get back to the grad show site from the MICA blog link?

### ISSUE THREAD

**Issue by annaehanson** [OOKB/mgs2017#69]
When you go to the blog but click “back” to try and get back to the MICA site it pops up with the 404 Error page.

**Comment by bjornmeansbear** [comment]
@webmasterkai this is an issue probably of me just throwing this junk up on Github Pages — is there a better way to host this so that those URLs work better?

for example also, just putting in https://2017.micagradshow.com/students or https://2017.micagradshow.com/details/recIq7NHCX8C3uoS3 gives you the 404 as well, but other sites we have handle this better, however they weren't just thrown up on gh by an imbecile (me)...

**Comment by webmasterkai** [comment]
This needs to be hosted on our react hosting server instead of github. `npm run deploy`

**Comment by webmasterkai** [comment]
Should be fixed now
